version: "3"

services:
  postgres:
    image: postgres:12-alpine
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
  cachet:
    volumes:
      - ./Cachet/app/:/var/www/html/app/
      - ./Cachet/storage/:/var/www/html/storage/
    build:
      context: .
      args:
        - cachet_ver=v2.5.1
        - archive_url=https://github.com/fiveai/Cachet/archive/refs/tags/v2.5.1.tar.gz
    ports:
      - 8000:8000
    links:
      - postgres:postgres
    environment:
      - TRUSTED_PROXIES=*
      - DB_DRIVER=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PREFIX=chq_
      - APP_LOG=errorlog
      - APP_KEY
      - APP_ENV=${APP_ENV:-production}
      - APP_URL
      - APP_DEBUG=false
      - DEBUG=false
      - MAIL_DRIVER
      - MAIL_HOST
      - MAIL_PORT
      - MAIL_USERNAME
      - MAIL_PASSWORD
      - MAIL_ADDRESS
      - MAIL_NAME
      - MAIL_ENCRYPTION


    depends_on:
      - postgres
    restart: on-failure
volumes:
  postgres_vol:
